- name: build
  tasks:
    - BABEL_ENV=build rollup -c
    - taskfile build-css

- name: build-css
  task: postcss example/css/src --use autoprefixer --base example/css/src -d example/css

- name: test
  tasks:
    - taskfile lint-js
    - taskfile lint-fs
    - - taskfile test-e2e
    - - - taskfile test-unit

- name: lint
  tasks:
    - taskfile lint-js
    - taskfile lint-fs

- name: start
  task: (cd example/server && BABEL_ENV=server babel-node default.js)

- name: watch
  task: concurrently 'BABEL_ENV=build rollup -c -w' 'npm run start'

- name: lint-fs
  tasks:
    - NODE_ENV=production npm run build
    - - gzip core.js -f
    - - - fslint --files=core.js.gz --limit=5500
    - - - - rm core.js.gz

- name: lint-js
  task: xo src/*.js

- name: test-e2e
  tasks:
    - BABEL_ENV=test-e2e rollup -c
    - - concurrently -k -s first 'npm run start' 'testcafe chrome:headless ./tests/e2e/*.test.js'
    - - - BABEL_ENV=build rollup -c
    - - - - rm core.js

- name: test-unit
  task: BABEL_ENV=test-unit ava

- name: prepublish
  tasks:
    - ncp src/ .

- name: postpublish
  tasks:
    - rm ./{switzerland,middleware,utilities,core}.js
    - - taskfile docker

- name: docker
  tasks:
    - docker build -t wildhoney/switzerland:latest .
    - - docker tag wildhoney/switzerland wildhoney/switzerland:$npm_package_version
    - - - docker push wildhoney/switzerland
